[supervisord]
nodaemon=true

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1280x720x24
priority=10
autorestart=true
environment=DISPLAY=":1"

[program:xfce]
command=/usr/bin/startxfce4
priority=20
autorestart=true
environment=DISPLAY=":1",HOME="/root"

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -forever -shared -nopw -listen 0.0.0.0 -rfbport 5900
priority=30
autorestart=true
environment=DISPLAY=":1"

[program:novnc]
command=/usr/share/novnc/utils/novnc_proxy --vnc 127.0.0.1:5900 --listen 6080
priority=40
autorestart=true
environment=HOME="/root"