"""Valid arguments for every registered tool, shared by the contract, end-to-end and recording tests.
The order is the order the end-to-end test runs them in, so file tools build on each other."""

SAMPLE_ARGS: dict[str, dict] = {
    "screenshot": {},
    "screen_diff": {},
    "wait_until_stable": {"timeout": 1.0},
    "click": {"x": 10, "y": 10},
    "move_mouse": {"x": 20, "y": 20},
    "double_click": {"x": 10, "y": 10},
    "scroll": {"direction": "down", "amount": 1},
    "drag": {"start_x": 10, "start_y": 10, "end_x": 30, "end_y": 30},
    "type_text": {"text": "zoo"},
    "press_key": {"key": "Escape"},
    "hotkey": {"keys": ["ctrl", "a"]},
    "windows_list": {},
    "window_focus": {"window_id": "1"},
    "window_minimize": {"window_id": "1"},
    "window_restore": {"window_id": "1"},
    "window_maximize": {"window_id": "1"},
    "window_unmaximize": {"window_id": "1"},
    "window_close": {"window_id": "1"},
    "installed_apps": {},
    "open_app": {"command": "xfce4-terminal"},
    "close_app": {"target": "Terminal"},
    "open_url": {"url": "https://example.com"},
    "fetch_url": {"url": "https://example.com"},
    "execute_command": {"command": "echo zoo"},
    "list_files": {"path": "."},
    "write_file": {"path": "zoo-test.txt", "content": "zoo"},
    "get_file_info": {"path": "zoo-test.txt"},
    "read_file": {"path": "zoo-test.txt"},
    "create_directory": {"path": "zoo-test-dir"},
    "copy_file": {"source": "zoo-test.txt", "destination": "zoo-test-moved.txt"},
    "move_file": {"source": "zoo-test-moved.txt", "destination": "zoo-test-copy.txt"},
    "delete_file": {"path": "zoo-test-copy.txt"},
}
