"""The database: a Postgres pool at DATABASE_URL and the sqlc-generated queries over it.

The queries (db/query.sql, generated into db/generated by sqlc) come back as SQLAlchemy clauses with :pN binds; the
connection wrapper rewrites each one once, to psycopg's %(pN)s style, and runs it on a plain psycopg connection.
"""

import os
import re
from collections.abc import Generator
from contextlib import contextmanager
from functools import cache
from typing import LiteralString, cast

import psycopg
from psycopg_pool import ConnectionPool

from db.generated.query import Querier  # Imported from your sqlc output output folder

# what a unique or foreign key violation raises
IntegrityError = psycopg.IntegrityError


class _Result:
    def __init__(self, cursor):
        self._cursor = cursor

    def first(self):
        return self._cursor.fetchone()

    def __iter__(self):
        return iter(self._cursor)


@cache
def psycopg_sql(sql: str) -> LiteralString:
    """sqlc's named binds (:p1) as psycopg's %(p1)s; % is escaped first, so a literal % in the SQL survives, and the
    colons SQLAlchemy escapes (\\: in a :: cast) come back."""
    binds = re.sub(r":p(\d+)\b", r"%(p\1)s", sql.replace("%", "%%"))
    return cast(LiteralString, binds.replace("\\:", ":"))


class Conn:
    def __init__(self, conn: psycopg.Connection):
        self._conn = conn

    def execute(self, clause, params: dict | None = None) -> _Result:
        sql = psycopg_sql(getattr(clause, "text", clause))
        return _Result(self._conn.execute(sql, params or {}))


def _configure(conn: psycopg.Connection) -> None:
    """Every session sees UTC, whatever timezone the database host runs on."""
    conn.execute("SET TIME ZONE 'UTC'")
    conn.commit()


class DatabaseManager:
    def __init__(self):
        self._pool: ConnectionPool | None = None
        self._url: str | None = None

    @property
    def url(self) -> str:
        """The database URL, for connections outside the pool (LISTEN in server/agent_api.py)."""
        if self._url is None:
            raise RuntimeError("DatabaseManager has not been initialised. Call init_db() first.")
        return self._url

    def init_db(self, url: str | None = None):
        """Connects to Postgres at url (DATABASE_URL by default), which must be a postgres:// or postgresql:// URL."""
        url = url if url is not None else (os.environ.get("DATABASE_URL") or None)
        self.close()
        if not url or not url.startswith(("postgres://", "postgresql://")):
            raise RuntimeError("DATABASE_URL must be a postgres:// or postgresql:// URL")
        self._url = url
        self._pool = ConnectionPool(
            url,
            min_size=1,
            max_size=int(os.environ.get("ZOO_DB_POOL_SIZE", "20")),
            configure=_configure,
            open=True,
        )

    def close(self):
        if self._pool is not None:
            self._pool.close()
            self._pool = None

    def wait(self, timeout: float = 30):
        """Blocks until the pool holds its minimum connections; tests use it so a mocked resolver can't race the
        pool's background fill."""
        if self._pool is not None:
            self._pool.wait(timeout=timeout)

    def get_client(self) -> Generator[Querier, None, None]:
        """FastAPI dependency: `db: Querier = Depends(db_manager.get_client)`"""
        if self._pool is None:
            raise RuntimeError("DatabaseManager has not been initialised. Call init_db() first.")
        with self._pool.connection() as conn:
            # the pool commits when the block ends cleanly and rolls back when it raises
            yield Querier(Conn(conn))  # type: ignore[arg-type]

    def session(self):
        return contextmanager(self.get_client)()

    def execute(self, sql: str, *params):
        """Runs a statement outside the generated queries (tests, maintenance), in Postgres's dialect."""
        if self._pool is None:
            raise RuntimeError("DatabaseManager has not been initialised. Call init_db() first.")
        with self._pool.connection() as conn:
            result = conn.execute(cast(LiteralString, sql.replace("?", "%s")), params)
            return list(result) if result.description else []


db_manager = DatabaseManager()
