"""The database: SQLite at DB_PATH by default, or Postgres when DATABASE_URL is a postgres:// URL.

The queries (db/query.sql, generated into db/generated by sqlc) are written for SQLite. On Postgres each one is
rewritten once, to what the Postgres schema (db/postgres) expects: placeholders, CURRENT_TIMESTAMP as zoo_now()
(the same text format SQLite stores), rowid as zoo_rowid, and two-argument MAX/MIN as GREATEST/LEAST."""

import os
import re
import sqlite3
from collections.abc import Generator
from contextlib import contextmanager
from functools import cache
from typing import Any

from db.generated.query import Querier  # Imported from your sqlc output output folder

# what a unique or foreign key violation raises, on either database
IntegrityError: tuple[type[Exception], ...] = (sqlite3.IntegrityError,)
try:
    import psycopg

    IntegrityError += (psycopg.IntegrityError,)
except ImportError:  # pragma: no cover - psycopg is a dependency; this keeps SQLite-only tooling working
    psycopg = None


class _Result:
    def __init__(self, cursor):
        self._cursor = cursor

    def first(self):
        return self._cursor.fetchone()

    def __iter__(self):
        return iter(self._cursor)


def _positional(params: dict | None) -> list:
    params = params or {}
    return [params[k] for k in sorted(params, key=lambda k: int(k[1:]))]


class SqliteConn:
    def __init__(self, conn: sqlite3.Connection):
        self._conn = conn

    def execute(self, clause, params: dict | None = None) -> _Result:
        sql = getattr(clause, "text", clause)
        return _Result(self._conn.execute(sql, _positional(params)))


def _greatest(sql: str) -> str:
    """MAX(a, b) and MIN(a, b), SQLite's scalar forms, as GREATEST and LEAST; one-argument aggregates stay."""
    out, i = [], 0
    for match in re.finditer(r"\b(MAX|MIN)\(", sql, flags=re.IGNORECASE):
        start = match.end()
        depth, comma = 1, False
        for j in range(start, len(sql)):
            if sql[j] == "(":
                depth += 1
            elif sql[j] == ")":
                depth -= 1
                if depth == 0:
                    break
            elif sql[j] == "," and depth == 1:
                comma = True
        if comma:
            out += [sql[i : match.start()], "GREATEST(" if match.group(1).upper() == "MAX" else "LEAST("]
            i = start
    return "".join(out) + sql[i:]


@cache
def postgres_sql(sql: str) -> str:
    sql = _greatest(sql)
    sql = re.sub(r"\bCURRENT_TIMESTAMP\b", "zoo_now()", sql)
    sql = re.sub(r"\browid\b", "zoo_rowid", sql)
    body = re.sub(r"^\s*--.*\n", "", sql, flags=re.MULTILINE).lstrip().upper()
    if body.startswith(("DELETE", "UPDATE")):
        # a claim's subquery: concurrent claims skip a row another one holds instead of both picking it
        sql = re.sub(r"(\bLIMIT 1)(\s*\))", r"\1 FOR UPDATE SKIP LOCKED\2", sql)
    return sql.replace("%", "%%").replace("?", "%s")


class PostgresConn:
    def __init__(self, conn):
        self._conn = conn

    def execute(self, clause, params: dict | None = None) -> _Result:
        sql = getattr(clause, "text", clause)
        return _Result(self._conn.execute(postgres_sql(sql), _positional(params)))


def _postgres_adapters(conn):
    """Postgres types that come back as SQLite's would: integer booleans in, integers (not Decimal) out of SUM."""
    import psycopg
    from psycopg.adapt import Dumper, Loader
    from psycopg.pq import Format

    class BoolAsInt(Dumper):
        oid = psycopg.adapters.types["int8"].oid
        format = Format.TEXT

        def dump(self, obj):
            return b"1" if obj else b"0"

    class Numeric(Loader):
        def load(self, data):
            text = bytes(data).decode()
            return float(text) if "." in text or "e" in text.lower() else int(text)

    conn.adapters.register_dumper(bool, BoolAsInt)
    conn.adapters.register_loader("numeric", Numeric)


class DatabaseManager:
    def __init__(self):
        self._db_path: str | None = None
        self._url: str | None = None
        self._pool: Any = None

    @property
    def postgres(self) -> bool:
        return self._url is not None

    def init_db(self, db_path: str | None = None, url: str | None = None):
        """Opens SQLite at db_path, or Postgres at url (DATABASE_URL by default when neither is given)."""
        url = url if url is not None else (None if db_path else os.environ.get("DATABASE_URL") or None)
        self.close()
        if url:
            if not url.startswith(("postgres://", "postgresql://")):
                raise RuntimeError("DATABASE_URL must be a postgres:// or postgresql:// URL")
            from psycopg_pool import ConnectionPool

            self._url, self._db_path = url, None
            self._pool = ConnectionPool(
                url,
                min_size=1,
                max_size=int(os.environ.get("ZOO_DB_POOL_SIZE", "20")),
                configure=_postgres_adapters,
                open=True,
            )
            return
        self._url, self._db_path = None, db_path or os.environ.get("DB_PATH", "./local.db")
        with sqlite3.connect(self._db_path) as conn:
            conn.execute("PRAGMA journal_mode=WAL;")

    def close(self):
        if self._pool is not None:
            self._pool.close()
            self._pool = None

    def get_client(self) -> Generator[Querier, None, None]:
        """FastAPI dependency: `db: Querier = Depends(db_manager.get_client)`"""
        if self._pool is not None:
            with self._pool.connection() as conn:
                # the pool commits when the block ends cleanly and rolls back when it raises
                yield Querier(PostgresConn(conn))  # type: ignore[arg-type]
            return
        if not self._db_path:
            raise RuntimeError("DatabaseManager has not been initialised. Call init_db() first.")

        conn = sqlite3.connect(self._db_path, check_same_thread=False, timeout=10)
        conn.row_factory = sqlite3.Row
        # foreign keys are off by default and the setting is per connection
        conn.execute("PRAGMA foreign_keys = ON;")

        try:
            querier = Querier(SqliteConn(conn))  # type: ignore[arg-type]
            yield querier
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            conn.close()

    def session(self):
        return contextmanager(self.get_client)()

    def execute(self, sql: str, *params):
        """Runs a statement outside the generated queries (tests, maintenance), in SQLite's dialect."""
        with self.session() as db:
            conn: Any = db._conn
            result = conn.execute(sql, {f"p{i + 1}": p for i, p in enumerate(params)})
            return list(result) if result._cursor.description else []


db_manager = DatabaseManager()
