// The link between zoo-node and the API. The node dials out and holds one Connect stream per API endpoint, so
// hosts need no inbound ports. Both sides authenticate with certificates from the API's node CA (mTLS); the node's
// certificate names it (CN = node id).
//
// Regenerate with `make proto` after changing this file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.2
// source: node.proto

package nodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// node -> API
type NodeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*NodeMessage_Hello
	//	*NodeMessage_Status
	//	*NodeMessage_Data
	//	*NodeMessage_Close
	//	*NodeMessage_Renew
	Body          isNodeMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeMessage) GetBody() isNodeMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *NodeMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*NodeMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *NodeMessage) GetStatus() *Status {
	if x != nil {
		if x, ok := x.Body.(*NodeMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *NodeMessage) GetData() *TunnelData {
	if x != nil {
		if x, ok := x.Body.(*NodeMessage_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *NodeMessage) GetClose() *TunnelClose {
	if x != nil {
		if x, ok := x.Body.(*NodeMessage_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *NodeMessage) GetRenew() *Renew {
	if x != nil {
		if x, ok := x.Body.(*NodeMessage_Renew); ok {
			return x.Renew
		}
	}
	return nil
}

type isNodeMessage_Body interface {
	isNodeMessage_Body()
}

type NodeMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type NodeMessage_Status struct {
	Status *Status `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

type NodeMessage_Data struct {
	Data *TunnelData `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type NodeMessage_Close struct {
	Close *TunnelClose `protobuf:"bytes,4,opt,name=close,proto3,oneof"`
}

type NodeMessage_Renew struct {
	Renew *Renew `protobuf:"bytes,5,opt,name=renew,proto3,oneof"`
}

func (*NodeMessage_Hello) isNodeMessage_Body() {}

func (*NodeMessage_Status) isNodeMessage_Body() {}

func (*NodeMessage_Data) isNodeMessage_Body() {}

func (*NodeMessage_Close) isNodeMessage_Body() {}

func (*NodeMessage_Renew) isNodeMessage_Body() {}

// API -> node
type ApiMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ApiMessage_Welcome
	//	*ApiMessage_Open
	//	*ApiMessage_Data
	//	*ApiMessage_Close
	//	*ApiMessage_Update
	//	*ApiMessage_Renewal
	Body          isApiMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiMessage) Reset() {
	*x = ApiMessage{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiMessage) ProtoMessage() {}

func (x *ApiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiMessage.ProtoReflect.Descriptor instead.
func (*ApiMessage) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *ApiMessage) GetBody() isApiMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ApiMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Body.(*ApiMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ApiMessage) GetOpen() *TunnelOpen {
	if x != nil {
		if x, ok := x.Body.(*ApiMessage_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *ApiMessage) GetData() *TunnelData {
	if x != nil {
		if x, ok := x.Body.(*ApiMessage_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *ApiMessage) GetClose() *TunnelClose {
	if x != nil {
		if x, ok := x.Body.(*ApiMessage_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *ApiMessage) GetUpdate() *UpdateChunk {
	if x != nil {
		if x, ok := x.Body.(*ApiMessage_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *ApiMessage) GetRenewal() *Renewal {
	if x != nil {
		if x, ok := x.Body.(*ApiMessage_Renewal); ok {
			return x.Renewal
		}
	}
	return nil
}

type isApiMessage_Body interface {
	isApiMessage_Body()
}

type ApiMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ApiMessage_Open struct {
	Open *TunnelOpen `protobuf:"bytes,2,opt,name=open,proto3,oneof"`
}

type ApiMessage_Data struct {
	Data *TunnelData `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type ApiMessage_Close struct {
	Close *TunnelClose `protobuf:"bytes,4,opt,name=close,proto3,oneof"`
}

type ApiMessage_Update struct {
	Update *UpdateChunk `protobuf:"bytes,5,opt,name=update,proto3,oneof"`
}

type ApiMessage_Renewal struct {
	Renewal *Renewal `protobuf:"bytes,6,opt,name=renewal,proto3,oneof"`
}

func (*ApiMessage_Welcome) isApiMessage_Body() {}

func (*ApiMessage_Open) isApiMessage_Body() {}

func (*ApiMessage_Data) isApiMessage_Body() {}

func (*ApiMessage_Close) isApiMessage_Body() {}

func (*ApiMessage_Update) isApiMessage_Body() {}

func (*ApiMessage_Renewal) isApiMessage_Body() {}

type Driver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // kata, runc, zoovm, hyperv
	Available     bool                   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"` // why it isn't available, or its version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Driver) Reset() {
	*x = Driver{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Driver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Driver) ProtoMessage() {}

func (x *Driver) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Driver.ProtoReflect.Descriptor instead.
func (*Driver) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *Driver) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Driver) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *Driver) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// The first message on a stream.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"` // linux, darwin, windows
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Drivers       []*Driver              `protobuf:"bytes,5,rep,name=drivers,proto3" json:"drivers,omitempty"`
	Targets       []string               `protobuf:"bytes,6,rep,name=targets,proto3" json:"targets,omitempty"` // what TunnelOpen can reach here: docker, ssh
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

func (x *Hello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Hello) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Hello) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Hello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Hello) GetDrivers() []*Driver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

func (x *Hello) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Endpoints     []string               `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"` // every API endpoint the node should hold a stream to
	StatusSeconds uint32                 `protobuf:"varint,3,opt,name=status_seconds,json=statusSeconds,proto3" json:"status_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{4}
}

func (x *Welcome) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Welcome) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Welcome) GetStatusSeconds() uint32 {
	if x != nil {
		return x.StatusSeconds
	}
	return 0
}

type Check struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Check) Reset() {
	*x = Check{}
	mi := &file_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check) ProtoMessage() {}

func (x *Check) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check.ProtoReflect.Descriptor instead.
func (*Check) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{5}
}

func (x *Check) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Check) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Check) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type Status struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Cpus            uint32                 `protobuf:"varint,1,opt,name=cpus,proto3" json:"cpus,omitempty"`
	MemoryTotal     uint64                 `protobuf:"varint,2,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryAvailable uint64                 `protobuf:"varint,3,opt,name=memory_available,json=memoryAvailable,proto3" json:"memory_available,omitempty"`
	DiskTotal       uint64                 `protobuf:"varint,4,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`
	DiskFree        uint64                 `protobuf:"varint,5,opt,name=disk_free,json=diskFree,proto3" json:"disk_free,omitempty"`
	Load            float64                `protobuf:"fixed64,6,opt,name=load,proto3" json:"load,omitempty"`         // 1-minute load average divided by cpus, or CPU use (0-1) where there is no load average
	Sandboxes       []string               `protobuf:"bytes,7,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"` // ids of the sandboxes running here
	Checks          []*Check               `protobuf:"bytes,8,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{6}
}

func (x *Status) GetCpus() uint32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *Status) GetMemoryTotal() uint64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *Status) GetMemoryAvailable() uint64 {
	if x != nil {
		return x.MemoryAvailable
	}
	return 0
}

func (x *Status) GetDiskTotal() uint64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *Status) GetDiskFree() uint64 {
	if x != nil {
		return x.DiskFree
	}
	return 0
}

func (x *Status) GetLoad() float64 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *Status) GetSandboxes() []string {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

func (x *Status) GetChecks() []*Check {
	if x != nil {
		return x.Checks
	}
	return nil
}

// A byte stream to one of the node's targets. The API opens it; either side closes it.
type TunnelOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelOpen) Reset() {
	*x = TunnelOpen{}
	mi := &file_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelOpen) ProtoMessage() {}

func (x *TunnelOpen) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelOpen.ProtoReflect.Descriptor instead.
func (*TunnelOpen) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{7}
}

func (x *TunnelOpen) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TunnelOpen) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type TunnelData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelData) Reset() {
	*x = TunnelData{}
	mi := &file_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelData) ProtoMessage() {}

func (x *TunnelData) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelData.ProtoReflect.Descriptor instead.
func (*TunnelData) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{8}
}

func (x *TunnelData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TunnelData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TunnelClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelClose) Reset() {
	*x = TunnelClose{}
	mi := &file_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelClose) ProtoMessage() {}

func (x *TunnelClose) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelClose.ProtoReflect.Descriptor instead.
func (*TunnelClose) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{9}
}

func (x *TunnelClose) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TunnelClose) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// A new build of zoo-node, in order; the node checks the hash, swaps it in after the last chunk and restarts.
type UpdateChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Last          bool                   `protobuf:"varint,5,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChunk) Reset() {
	*x = UpdateChunk{}
	mi := &file_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChunk) ProtoMessage() {}

func (x *UpdateChunk) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChunk.ProtoReflect.Descriptor instead.
func (*UpdateChunk) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateChunk) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateChunk) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *UpdateChunk) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UpdateChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

// The node asks for a new certificate before its own expires, with a CSR for a new key.
type Renew struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Csr           []byte                 `protobuf:"bytes,1,opt,name=csr,proto3" json:"csr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Renew) Reset() {
	*x = Renew{}
	mi := &file_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Renew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Renew) ProtoMessage() {}

func (x *Renew) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Renew.ProtoReflect.Descriptor instead.
func (*Renew) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{11}
}

func (x *Renew) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

type Renewal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   []byte                 `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Renewal) Reset() {
	*x = Renewal{}
	mi := &file_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Renewal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Renewal) ProtoMessage() {}

func (x *Renewal) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Renewal.ProtoReflect.Descriptor instead.
func (*Renewal) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{12}
}

func (x *Renewal) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *Renewal) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\vzoo.node.v1\"\xfd\x01\n" +
	"\vNodeMessage\x12*\n" +
	"\x05hello\x18\x01 \x01(\v2\x12.zoo.node.v1.HelloH\x00R\x05hello\x12-\n" +
	"\x06status\x18\x02 \x01(\v2\x13.zoo.node.v1.StatusH\x00R\x06status\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x17.zoo.node.v1.TunnelDataH\x00R\x04data\x120\n" +
	"\x05close\x18\x04 \x01(\v2\x18.zoo.node.v1.TunnelCloseH\x00R\x05close\x12*\n" +
	"\x05renew\x18\x05 \x01(\v2\x12.zoo.node.v1.RenewH\x00R\x05renewB\x06\n" +
	"\x04body\"\xbc\x02\n" +
	"\n" +
	"ApiMessage\x120\n" +
	"\awelcome\x18\x01 \x01(\v2\x14.zoo.node.v1.WelcomeH\x00R\awelcome\x12-\n" +
	"\x04open\x18\x02 \x01(\v2\x17.zoo.node.v1.TunnelOpenH\x00R\x04open\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x17.zoo.node.v1.TunnelDataH\x00R\x04data\x120\n" +
	"\x05close\x18\x04 \x01(\v2\x18.zoo.node.v1.TunnelCloseH\x00R\x05close\x122\n" +
	"\x06update\x18\x05 \x01(\v2\x18.zoo.node.v1.UpdateChunkH\x00R\x06update\x120\n" +
	"\arenewal\x18\x06 \x01(\v2\x14.zoo.node.v1.RenewalH\x00R\arenewalB\x06\n" +
	"\x04body\"R\n" +
	"\x06Driver\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\xaa\x01\n" +
	"\x05Hello\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12-\n" +
	"\adrivers\x18\x05 \x03(\v2\x13.zoo.node.v1.DriverR\adrivers\x12\x18\n" +
	"\atargets\x18\x06 \x03(\tR\atargets\"o\n" +
	"\aWelcome\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x1c\n" +
	"\tendpoints\x18\x02 \x03(\tR\tendpoints\x12%\n" +
	"\x0estatus_seconds\x18\x03 \x01(\rR\rstatusSeconds\"C\n" +
	"\x05Check\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\x84\x02\n" +
	"\x06Status\x12\x12\n" +
	"\x04cpus\x18\x01 \x01(\rR\x04cpus\x12!\n" +
	"\fmemory_total\x18\x02 \x01(\x04R\vmemoryTotal\x12)\n" +
	"\x10memory_available\x18\x03 \x01(\x04R\x0fmemoryAvailable\x12\x1d\n" +
	"\n" +
	"disk_total\x18\x04 \x01(\x04R\tdiskTotal\x12\x1b\n" +
	"\tdisk_free\x18\x05 \x01(\x04R\bdiskFree\x12\x12\n" +
	"\x04load\x18\x06 \x01(\x01R\x04load\x12\x1c\n" +
	"\tsandboxes\x18\a \x03(\tR\tsandboxes\x12*\n" +
	"\x06checks\x18\b \x03(\v2\x12.zoo.node.v1.CheckR\x06checks\"4\n" +
	"\n" +
	"TunnelOpen\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\"0\n" +
	"\n" +
	"TunnelData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"3\n" +
	"\vTunnelClose\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"{\n" +
	"\vUpdateChunk\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x12\n" +
	"\x04last\x18\x05 \x01(\bR\x04last\"\x19\n" +
	"\x05Renew\x12\x10\n" +
	"\x03csr\x18\x01 \x01(\fR\x03csr\"A\n" +
	"\aRenewal\x12 \n" +
	"\vcertificate\x18\x01 \x01(\fR\vcertificate\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2H\n" +
	"\x04Node\x12@\n" +
	"\aConnect\x12\x18.zoo.node.v1.NodeMessage\x1a\x17.zoo.node.v1.ApiMessage(\x010\x01B$Z\"github.com/chann44/zoo/node/nodepbb\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_node_proto_goTypes = []any{
	(*NodeMessage)(nil), // 0: zoo.node.v1.NodeMessage
	(*ApiMessage)(nil),  // 1: zoo.node.v1.ApiMessage
	(*Driver)(nil),      // 2: zoo.node.v1.Driver
	(*Hello)(nil),       // 3: zoo.node.v1.Hello
	(*Welcome)(nil),     // 4: zoo.node.v1.Welcome
	(*Check)(nil),       // 5: zoo.node.v1.Check
	(*Status)(nil),      // 6: zoo.node.v1.Status
	(*TunnelOpen)(nil),  // 7: zoo.node.v1.TunnelOpen
	(*TunnelData)(nil),  // 8: zoo.node.v1.TunnelData
	(*TunnelClose)(nil), // 9: zoo.node.v1.TunnelClose
	(*UpdateChunk)(nil), // 10: zoo.node.v1.UpdateChunk
	(*Renew)(nil),       // 11: zoo.node.v1.Renew
	(*Renewal)(nil),     // 12: zoo.node.v1.Renewal
}
var file_node_proto_depIdxs = []int32{
	3,  // 0: zoo.node.v1.NodeMessage.hello:type_name -> zoo.node.v1.Hello
	6,  // 1: zoo.node.v1.NodeMessage.status:type_name -> zoo.node.v1.Status
	8,  // 2: zoo.node.v1.NodeMessage.data:type_name -> zoo.node.v1.TunnelData
	9,  // 3: zoo.node.v1.NodeMessage.close:type_name -> zoo.node.v1.TunnelClose
	11, // 4: zoo.node.v1.NodeMessage.renew:type_name -> zoo.node.v1.Renew
	4,  // 5: zoo.node.v1.ApiMessage.welcome:type_name -> zoo.node.v1.Welcome
	7,  // 6: zoo.node.v1.ApiMessage.open:type_name -> zoo.node.v1.TunnelOpen
	8,  // 7: zoo.node.v1.ApiMessage.data:type_name -> zoo.node.v1.TunnelData
	9,  // 8: zoo.node.v1.ApiMessage.close:type_name -> zoo.node.v1.TunnelClose
	10, // 9: zoo.node.v1.ApiMessage.update:type_name -> zoo.node.v1.UpdateChunk
	12, // 10: zoo.node.v1.ApiMessage.renewal:type_name -> zoo.node.v1.Renewal
	2,  // 11: zoo.node.v1.Hello.drivers:type_name -> zoo.node.v1.Driver
	5,  // 12: zoo.node.v1.Status.checks:type_name -> zoo.node.v1.Check
	0,  // 13: zoo.node.v1.Node.Connect:input_type -> zoo.node.v1.NodeMessage
	1,  // 14: zoo.node.v1.Node.Connect:output_type -> zoo.node.v1.ApiMessage
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	file_node_proto_msgTypes[0].OneofWrappers = []any{
		(*NodeMessage_Hello)(nil),
		(*NodeMessage_Status)(nil),
		(*NodeMessage_Data)(nil),
		(*NodeMessage_Close)(nil),
		(*NodeMessage_Renew)(nil),
	}
	file_node_proto_msgTypes[1].OneofWrappers = []any{
		(*ApiMessage_Welcome)(nil),
		(*ApiMessage_Open)(nil),
		(*ApiMessage_Data)(nil),
		(*ApiMessage_Close)(nil),
		(*ApiMessage_Update)(nil),
		(*ApiMessage_Renewal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
