"""Writes keysyms.go, X11's keysym names, from keysymdef.h and XF86keysym.h (Debian: x11proto-dev).

python3 gen_keysyms.py /usr/include/X11/keysymdef.h /usr/include/X11/XF86keysym.h > keysyms.go
"""

import re
import sys

DEFINE = re.compile(r"^#define\s+(XF86)?XK_([A-Za-z0-9_]+)\s+(0x[0-9a-fA-F]+)")

names: dict[str, int] = {}
for path in sys.argv[1:]:
    with open(path) as header:
        for line in header:
            m = DEFINE.match(line)
            if m:
                names.setdefault((m.group(1) or "") + m.group(2), int(m.group(3), 16))

print("// Code generated by gen_keysyms.py from X11's keysymdef.h and XF86keysym.h. DO NOT EDIT.")
print()
print("package main")
print()
print("var keysymNames = map[string]uint32{")
for name, value in names.items():
    print(f'\t"{name}": {value:#x},')
print("}")
