/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppMonitoringRouteImport } from './routes/_app/monitoring'
import { Route as AppNetworkRouteImport } from './routes/_app/network'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as ViewSandboxIdRouteImport } from './routes/view.$sandboxId'
import { Route as AppComputersIndexRouteImport } from './routes/_app/computers/index'
import { Route as AppComputersComputerIdRouteImport } from './routes/_app/computers/$computerId'
import { Route as AppSandboxesIndexRouteImport } from './routes/_app/sandboxes/index'
import { Route as AppWorkspacesIndexRouteImport } from './routes/_app/workspaces/index'
import { Route as AppWorkspacesWorkspaceIdRouteImport } from './routes/_app/workspaces/$workspaceId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringRoute = AppMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ViewSandboxIdRoute = ViewSandboxIdRouteImport.update({
  id: '/view/$sandboxId',
  path: '/view/$sandboxId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppComputersIndexRoute = AppComputersIndexRouteImport.update({
  id: '/computers/',
  path: '/computers/',
  getParentRoute: () => AppRoute,
} as any)
const AppComputersComputerIdRoute = AppComputersComputerIdRouteImport.update({
  id: '/computers/$computerId',
  path: '/computers/$computerId',
  getParentRoute: () => AppRoute,
} as any)
const AppSandboxesIndexRoute = AppSandboxesIndexRouteImport.update({
  id: '/sandboxes/',
  path: '/sandboxes/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesIndexRoute = AppWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesWorkspaceIdRoute =
  AppWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/monitoring': typeof AppMonitoringRoute
  '/network': typeof AppNetworkRoute
  '/settings': typeof AppSettingsRoute
  '/view/$sandboxId': typeof ViewSandboxIdRoute
  '/computers/$computerId': typeof AppComputersComputerIdRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/computers/': typeof AppComputersIndexRoute
  '/sandboxes/': typeof AppSandboxesIndexRoute
  '/workspaces/': typeof AppWorkspacesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/monitoring': typeof AppMonitoringRoute
  '/network': typeof AppNetworkRoute
  '/settings': typeof AppSettingsRoute
  '/view/$sandboxId': typeof ViewSandboxIdRoute
  '/': typeof AppIndexRoute
  '/computers/$computerId': typeof AppComputersComputerIdRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/computers': typeof AppComputersIndexRoute
  '/sandboxes': typeof AppSandboxesIndexRoute
  '/workspaces': typeof AppWorkspacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/monitoring': typeof AppMonitoringRoute
  '/_app/network': typeof AppNetworkRoute
  '/_app/settings': typeof AppSettingsRoute
  '/view/$sandboxId': typeof ViewSandboxIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/computers/$computerId': typeof AppComputersComputerIdRoute
  '/_app/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/_app/computers/': typeof AppComputersIndexRoute
  '/_app/sandboxes/': typeof AppSandboxesIndexRoute
  '/_app/workspaces/': typeof AppWorkspacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/monitoring'
    | '/network'
    | '/settings'
    | '/view/$sandboxId'
    | '/computers/$computerId'
    | '/workspaces/$workspaceId'
    | '/computers/'
    | '/sandboxes/'
    | '/workspaces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/monitoring'
    | '/network'
    | '/settings'
    | '/view/$sandboxId'
    | '/'
    | '/computers/$computerId'
    | '/workspaces/$workspaceId'
    | '/computers'
    | '/sandboxes'
    | '/workspaces'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/monitoring'
    | '/_app/network'
    | '/_app/settings'
    | '/view/$sandboxId'
    | '/_app/'
    | '/_app/computers/$computerId'
    | '/_app/workspaces/$workspaceId'
    | '/_app/computers/'
    | '/_app/sandboxes/'
    | '/_app/workspaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ViewSandboxIdRoute: typeof ViewSandboxIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitoring': {
      id: '/_app/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AppMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network': {
      id: '/_app/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/view/$sandboxId': {
      id: '/view/$sandboxId'
      path: '/view/$sandboxId'
      fullPath: '/view/$sandboxId'
      preLoaderRoute: typeof ViewSandboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/computers/': {
      id: '/_app/computers/'
      path: '/computers'
      fullPath: '/computers/'
      preLoaderRoute: typeof AppComputersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/computers/$computerId': {
      id: '/_app/computers/$computerId'
      path: '/computers/$computerId'
      fullPath: '/computers/$computerId'
      preLoaderRoute: typeof AppComputersComputerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sandboxes/': {
      id: '/_app/sandboxes/'
      path: '/sandboxes'
      fullPath: '/sandboxes/'
      preLoaderRoute: typeof AppSandboxesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces/': {
      id: '/_app/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AppWorkspacesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces/$workspaceId': {
      id: '/_app/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMonitoringRoute: typeof AppMonitoringRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppComputersComputerIdRoute: typeof AppComputersComputerIdRoute
  AppWorkspacesWorkspaceIdRoute: typeof AppWorkspacesWorkspaceIdRoute
  AppComputersIndexRoute: typeof AppComputersIndexRoute
  AppSandboxesIndexRoute: typeof AppSandboxesIndexRoute
  AppWorkspacesIndexRoute: typeof AppWorkspacesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMonitoringRoute: AppMonitoringRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppComputersComputerIdRoute: AppComputersComputerIdRoute,
  AppWorkspacesWorkspaceIdRoute: AppWorkspacesWorkspaceIdRoute,
  AppComputersIndexRoute: AppComputersIndexRoute,
  AppSandboxesIndexRoute: AppSandboxesIndexRoute,
  AppWorkspacesIndexRoute: AppWorkspacesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ViewSandboxIdRoute: ViewSandboxIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
