/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppMonitoringRouteImport } from './routes/_app/monitoring'
import { Route as AppServersRouteImport } from './routes/_app/servers'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as ViewSandboxIdRouteImport } from './routes/view.$sandboxId'
import { Route as AppSandboxesIndexRouteImport } from './routes/_app/sandboxes/index'
import { Route as AppSandboxesSandboxIdRouteImport } from './routes/_app/sandboxes/$sandboxId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringRoute = AppMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppServersRoute = AppServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ViewSandboxIdRoute = ViewSandboxIdRouteImport.update({
  id: '/view/$sandboxId',
  path: '/view/$sandboxId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSandboxesIndexRoute = AppSandboxesIndexRouteImport.update({
  id: '/sandboxes/',
  path: '/sandboxes/',
  getParentRoute: () => AppRoute,
} as any)
const AppSandboxesSandboxIdRoute = AppSandboxesSandboxIdRouteImport.update({
  id: '/sandboxes/$sandboxId',
  path: '/sandboxes/$sandboxId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/monitoring': typeof AppMonitoringRoute
  '/servers': typeof AppServersRoute
  '/settings': typeof AppSettingsRoute
  '/view/$sandboxId': typeof ViewSandboxIdRoute
  '/sandboxes/$sandboxId': typeof AppSandboxesSandboxIdRoute
  '/sandboxes/': typeof AppSandboxesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/monitoring': typeof AppMonitoringRoute
  '/servers': typeof AppServersRoute
  '/settings': typeof AppSettingsRoute
  '/view/$sandboxId': typeof ViewSandboxIdRoute
  '/': typeof AppIndexRoute
  '/sandboxes/$sandboxId': typeof AppSandboxesSandboxIdRoute
  '/sandboxes': typeof AppSandboxesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/monitoring': typeof AppMonitoringRoute
  '/_app/servers': typeof AppServersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/view/$sandboxId': typeof ViewSandboxIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/sandboxes/$sandboxId': typeof AppSandboxesSandboxIdRoute
  '/_app/sandboxes/': typeof AppSandboxesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/monitoring'
    | '/servers'
    | '/settings'
    | '/view/$sandboxId'
    | '/sandboxes/$sandboxId'
    | '/sandboxes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/monitoring'
    | '/servers'
    | '/settings'
    | '/view/$sandboxId'
    | '/'
    | '/sandboxes/$sandboxId'
    | '/sandboxes'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/monitoring'
    | '/_app/servers'
    | '/_app/settings'
    | '/view/$sandboxId'
    | '/_app/'
    | '/_app/sandboxes/$sandboxId'
    | '/_app/sandboxes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ViewSandboxIdRoute: typeof ViewSandboxIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitoring': {
      id: '/_app/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AppMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers': {
      id: '/_app/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AppServersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/view/$sandboxId': {
      id: '/view/$sandboxId'
      path: '/view/$sandboxId'
      fullPath: '/view/$sandboxId'
      preLoaderRoute: typeof ViewSandboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sandboxes/': {
      id: '/_app/sandboxes/'
      path: '/sandboxes'
      fullPath: '/sandboxes/'
      preLoaderRoute: typeof AppSandboxesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sandboxes/$sandboxId': {
      id: '/_app/sandboxes/$sandboxId'
      path: '/sandboxes/$sandboxId'
      fullPath: '/sandboxes/$sandboxId'
      preLoaderRoute: typeof AppSandboxesSandboxIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMonitoringRoute: typeof AppMonitoringRoute
  AppServersRoute: typeof AppServersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSandboxesSandboxIdRoute: typeof AppSandboxesSandboxIdRoute
  AppSandboxesIndexRoute: typeof AppSandboxesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMonitoringRoute: AppMonitoringRoute,
  AppServersRoute: AppServersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppSandboxesSandboxIdRoute: AppSandboxesSandboxIdRoute,
  AppSandboxesIndexRoute: AppSandboxesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ViewSandboxIdRoute: ViewSandboxIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
